name: AWS Planetiler

on:
  workflow_dispatch

jobs:
  aws-planetiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create instance
        run: |
          aws ec2 run-instances --image-id ${{ secrets.AWS_IMAGE_ID }} --count 1 \
            --instance-type ${{ secrets.AWS_INSTANCE_TYPE }} --key-name ${{ secrets.AWS_KEY_NAME }} \
            --security-group-ids ${{ secrets.AWS_SECURITY_GROUP_IDS }} --subnet-id ${{ secrets.AWS_SUBNET_ID }} \
            > run-instances-output.json

      - name: Get instance id
        id: instance_id
        run: |
          echo ::set-output name=instance_id::$(grep -oP '(?<="InstanceId": ")[^"]*' run-instances-output.json | head -1)

      - name: Wait until instance ready
        run: aws ec2 wait instance-status-ok --instance-ids ${{ steps.instance_id.outputs.instance_id }}

      - name: Get public DNS name
        id: public_dns_name
        run: |
          aws ec2 describe-instances --instance-ids ${{ steps.instance_id.outputs.instance_id }} > describe-instances-output.json
          echo ::set-output name=public_dns_name::$(grep -oP '(?<="PublicDnsName": ")[^"]*' describe-instances-output.json | head -1)

      - name: Install docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.public_dns_name.outputs.public_dns_name }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo yum update -y
            sudo amazon-linux-extras install docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user

      - name: Run planetiler
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.public_dns_name.outputs.public_dns_name }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker run -e \
              JAVA_TOOL_OPTIONS="-Xmx7g" \
              -v "$(pwd)/data":/data \
              ghcr.io/onthegomap/planetiler:latest \
              --download \
              --area=switzerland
            ls -lah data

      - name: SCP output.mbtiles to target
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.public_dns_name.outputs.public_dns_name }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "${{ secrets.TARGET_SSH_PRIVATE_KEY }}" | base64 -d > .ssh/target
            chmod 600 .ssh/target
            eval `ssh-agent`
            ssh-add .ssh/target
            scp -o StrictHostKeyChecking=no data/output.mbtiles ${{ secrets.TARGET_USERNAME }}@${{ secrets.TARGET_HOST }}:${{ secrets.TARGET_FOLDER }}

      - name: Terminate instance
        if: always()
      - run: |
          aws ec2 terminate-instances --instance-ids ${{ steps.instance_id.outputs.instance_id }}
